# -------------------------------------------------------------------------
# This source file is a part of Placid
# 
# For the latest info, see http://www.marrin.org/
# 
# Copyright (c) 2018-2019, Chris Marrin
# All rights reserved.
#
# Use of this source code is governed by the MIT license that can be
# found in the LICENSE file.

PLACIDDIR = ../../Placid
BUILDDIR = build
PRODUCT = hello

LIBS = $(PLACIDDIR)/libplacid.a

SRC =	main.cpp \

all: checkdirs $(PRODUCT)

include $(PLACIDDIR)/Common.mk

