PLATFORMSRC = \
	RPi/start.S \
	RPi/ldivmod.S \
	RPi/idivmod.S \
	RPi/uidivmod.S \
	RPi/RPiBare.cpp \
	RPi/RPiException.cpp \
	RPi/RPiGPIO.cpp \
	RPi/RPiGraphics.cpp \
	RPi/RPiInterruptManager.cpp \
	RPi/RPiMailbox.cpp \
	RPi/RPiMemory.cpp \
	RPi/RPiMemoryMin.cpp \
	RPi/RPiMutex.cpp \
	RPi/RPiReceiveFile.cpp \
	RPi/RPiSDCard.cpp \
	RPi/RPiSerial.cpp \
	RPi/RPiSPIMaster.cpp \
	RPi/RPiTimer.cpp \
